title: Masatoshi Nishiguchi
description: Software engineer who strives to write code with clean architecture, using Ruby, JS, React and more.
permalink: pretty
url: "https://mnishiguchi.com"
baseurl: ""
ga_id: "UA-76603801-1"
author:
  name: Masatoshi Nishiguchi
sass:
  sass_dir: _sass # the directory that contains sass partials
  style: :compressed
include:
  - _pages
  - _redirects
exclude:
  - admin/index.js
  - bin
  - LICENSE.txt
  - node_modules
  - package.json
  - README.md
  - yarn.lock
plugins:
  - jekyll-gist
  - jekyll-seo-tag
# https://fontawesome.com/v4.7.0/icons/
icon_links:
  - [home, /]
  - [sticky-note, /posts]
  - [github, "https://github.com/mnishiguchi"]
  - [linkedin, "https://linkedin.com/in/mnishiguchi"]
  - [stack-overflow, "https://stackoverflow.com/users/3837223/mnishiguchi"]
excerpt_separator: "\n\n\n" # two blank lines
read_more_text: "read more »"
empty_array: []
