# Default config: https://jekyllrb.com/docs/configuration/default/
title: Masatoshi Nishiguchi
short_title: Masa
theme_color: "#082031"
description: Software engineer who strives to write maintainable clean apps using Ruby, JS, React and more.
permalink: pretty
url: "https://mnishiguchi.com"
baseurl: ""
ga_id: "UA-76603801-1"
icon_dir: "/assets/images/icons"
author:
  name: Masatoshi Nishiguchi
include:
  - _pages
exclude:
  - .*
  - admin/index.js
  - assets/images/brands
  - assets/images/fontawesome
  - bin
  - LICENSE*
  - node_modules
  - package.json
  - Procfile.dev
  - README.md
  - webpack.config.js
  - yarn.lock
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-inline-svg
read_more_text: "read more »"
