# Default config: https://jekyllrb.com/docs/configuration/default/
title: Masatoshi Nishiguchi
description: Software engineer who strives to write code with clean architecture, using Ruby, JS, React and more.
permalink: pretty
url: "https://mnishiguchi-jekyll.netlify.app"
baseurl: ""
# ga_id: "UA-76603801-1"
author:
  name: Masatoshi Nishiguchi
include:
  - _pages
  - _redirects
exclude:
  - .*
  - admin/index.js
  - bin
  - LICENSE*
  - node_modules
  - package.json
  - README.md
  - webpack.config.js
  - yarn.lock
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-inline-svg
# https://fontawesome.com/v4.7.0/icons/
icon_links:
  - [home, /]
  - [sticky-note, /posts]
  - [github, "https://github.com/mnishiguchi"]
  - [linkedin, "https://linkedin.com/in/mnishiguchi"]
  - [stack-overflow, "https://stackoverflow.com/users/3837223/mnishiguchi"]
read_more_text: "read more »"
empty_array: []
